name: Update README with new blog post

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Update README
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        if [[ $COMMIT_MSG == *"create post:"* ]]; then
          TITLE=$(echo "$COMMIT_MSG" | sed -n 's/.*create post: *\(.*\)/\1/p')
          SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
          NEW_LINK="- [$TITLE](https://cosmicoppai.hashnode.dev/$SLUG)"
          
          # Check if Blogs section exists
          if ! grep -q "## Blogs" README.md; then
            echo "Error: Blogs section not found in README.md"
            exit 1
          fi
          
          # Extract existing content of the Blogs section
          BLOGS_CONTENT=$(sed -n '/^## Blogs/,/^##/p' README.md)
          
          # Prepare new content
          NEW_CONTENT="## Blogs\n\n$NEW_LINK"
          
          # Add existing links, skipping duplicates and limiting to 5
          COUNTER=1
          echo "$BLOGS_CONTENT" | while read -r line; do
            if [[ $line != "$NEW_LINK" && $line == -* && $COUNTER -lt 5 ]]; then
              NEW_CONTENT="${NEW_CONTENT}\n$line"
              COUNTER=$((COUNTER + 1))
            elif [[ $line == ##* && $line != "## Blogs" ]]; then
              # We've reached the next section, add it and break
              NEW_CONTENT="${NEW_CONTENT}\n\n$line"
              break
            fi
          done
          
          # Update README.md
          sed -i '/^## Blogs/,/^##/c\'"$NEW_CONTENT" README.md
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md with new blog post link" || echo "No changes to commit"
          git push
        else
          echo "No new blog post to add to README.md."
        fi
