name: Update README with new blog post

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Update README
      shell: bash
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        if [[ $COMMIT_MSG == *"create post:"* ]]; then
          TITLE=$(echo "$COMMIT_MSG" | sed -n 's/.*create post: *\(.*\)/\1/p')
          SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
          NEW_LINK="- [$TITLE](https://cosmicoppai.hashnode.dev/$SLUG)"
          
          # Check if Blogs section exists
          if ! grep -q "## Blogs" README.md; then
            echo "Error: Blogs section not found in README.md"
            exit 1
          fi
          
          # Update README.md
          awk -v new_link="$NEW_LINK" '
          BEGIN {in_blogs=0; count=0; printed_new=0}
          /^## Blogs/ {in_blogs=1; print; print ""; print new_link; printed_new=1; next}
          /^##/ && in_blogs {in_blogs=0; print; next}
          in_blogs && /^- / {
            if (count < 4 && $0 != new_link) {
              print
              count++
            }
            next
          }
          {print}
          ' README.md > README.tmp && mv README.tmp README.md
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md with new blog post link" || echo "No changes to commit"
          git push
        else
          echo "No new blog post to add to README.md."
        fi
